// <auto-generated />
namespace _PaintTool_ver2_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sendgrid_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sendgrid_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201601281733444_sendgrid_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
