// <auto-generated />
namespace _PaintTool_ver2_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_FirstName_LastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_FirstName_LastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201601270650105_added_FirstName_LastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
